[package]
name = "rust-fundamental-finance"
version = "0.1.0"
edition = "2021"
author= "Arman Riazi"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
